In [7]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import StandardScaler, LabelEncoder
from sklearn.model_selection import train_test_split

df = pd.read_csv("~/Projects/Python/Loan_Default_Prediction/Data/cleaned_loan_data.csv")
df.head()

,ID,year,loan_limit,Gender,approv_in_adv,loan_type,loan_purpose,Credit_Worthiness,open_credit,business_or_commercial,...,credit_type,Credit_Score,co-applicant_credit_type,age,submission_of_application,LTV,Region,Security_Type,Status,dtir1
0,24890,2019,cf,Sex Not Available,nopre,type1,p1,l1,nopc,nob/c,...,EXP,758,CIB,25-34,to_inst,98.728814,south,direct,1,45.0
1,24891,2019,cf,Male,nopre,type2,p1,l1,nopc,b/c,...,EQUI,552,EXP,55-64,to_inst,75.135870,North,direct,1,39.0
2,24892,2019,cf,Male,pre,type1,p1,l1,nopc,nob/c,...,EXP,834,CIB,35-44,to_inst,80.019685,south,direct,0,46.0
3,24893,2019,cf,Male,nopre,type1,p4,l1,nopc,nob/c,...,EXP,587,CIB,45-54,not_inst,69.376900,North,direct,0,42.0
4,24894,2019,cf,Joint,pre,type1,p1,l1,nopc,nob/c,...,CRIF,602,EXP,25-34,not_inst,91.886544,North,direct,0,39.0

In [8]:
# Label encoding for binary categorical columns

label_encoder = LabelEncoder()
binary_cols = [col for col in df.columns if df[col].nunique()== 2]

for col in binary_cols:
    df[col] = label_encoder.fit_transform(df[col])

In [9]:
# One-Hot Encoding for other categorical columns

df = pd.get_dummies(df, drop_first=True)

In [10]:
# Scale numerical features

# Exclude target variable before scaling
numerical_cols = df.select_dtypes(include=['number']).columns.tolist()
numerical_cols.remove('Status')

#Apply standard scaling to features only
scaler = StandardScaler()
df[numerical_cols] = scaler.fit_transform(df[numerical_cols])

# Exclude target variable before scaling
numerical_cols = df.select_dtypes(include=['number']).columns.tolist()
numerical_cols.remove('Status')  

# Apply Standard Scaling to features only
scaler = StandardScaler()
df[numerical_cols] = scaler.fit_transform(df[numerical_cols])

In [11]:
# Define features and target variables

X = df.drop(columns=['Status'])
y = df['Status']

# Split into training and testing sets

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [12]:
# Save processed datasets for model training

X_train.to_csv("~/Projects/Python/Loan_Default_Prediction/Data/X_train.csv", index=False)
X_test.to_csv("~/Projects/Python/Loan_Default_Prediction/Data/X_test.csv", index=False)
y_train.to_csv("~/Projects/Python/Loan_Default_Prediction/Data/y_train.csv", index=False)
y_test.to_csv("~/Projects/Python/Loan_Default_Prediction/Data/y_test.csv", index=False)